### ISSUE TITLE
method stringtosign should not have \n but a space

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/http-signatures-php#1]
According to specification, there will be one space after each key:  value pair not new line as is shown
in this snippet of code. 
if the key parameter has no value, still will be a space after colon :  
 private static function stringToSign(array $headers): string
    {
        $string = '';
        foreach ($headers as $k=>$v) { $string.="$k: $v\n"; }
        return trim($string);
    }

**Comment by inghamn** [comment]
The spec specifically says to separate them with the new line character.

https://tools.ietf.org/html/draft-cavage-http-signatures-12#section-2.3
